### ISSUE TITLE
Go 1.9.1 compatibility broken

### ISSUE THREAD

**Issue by ffeast** [prebid/prebid-server#895]
Hi

From the https://github.com/prebid/prebid-server#installation guide:
`First install Go 1.9.1 or later and dep`

However, it doesn't seem to build with 1.9.1:

```
./validate.sh 
# github.com/prebid/prebid-server/macros
macros/macros.go:22:16: undefined: strings.Builder
# github.com/prebid/prebid-server/macros
macros/macros.go:22:16: undefined: strings.Builder
FAIL    github.com/prebid/prebid-server [build failed]
FAIL    github.com/prebid/prebid-server/adapters [build failed]
FAIL    github.com/prebid/prebid-server/adapters/33across [build failed]

```

It seems to fail because of `strings.Builder` used in `macros.go`
The suggestion is to either update the docs or switch to `bytes.Buffer` if 1.9.1 still needs to be supported

**Comment by benjaminch** [comment]
Hello there ! 
I would be happy to work on this one ! :)
