### ISSUE TITLE
Tests Failing In Master

### ISSUE THREAD

**Issue by Kevin-P-Kerr** [prebid/prebid-server#940]
Hi All,

I'm working on the TripleLift s2s adapter, but there a few things I don't understand but configuring/testing this application. 

I'm working with go version 1.12.6 darwin/amd 64.

First, it seems like `dep ensure` only works on `master`.  When I create a new dev branch--with no other alteration-- I run into errors that look like 
```
Subpackage github.com/prebid/prebid-server ... is missing (Required by ((root))
```
 But running on master is fine.  

Second, `validate` fails on master.  In particular, it can't seem to build certain packages because of missing constants. 
```
# prebid-server/endpoints/openrtb2 [prebid-server/endpoints/openrtb2.test]
endpoints/openrtb2/video_auction.go:380:5: unknown field 'HbPb' in struct literal of type openrtb_ext.VideoTargeting
endpoints/openrtb2/video_auction.go:381:5: unknown field 'HbPbCatDur' in struct literal of type openrtb_ext.VideoTargeting
endpoints/openrtb2/video_auction.go:382:5: unknown field 'HbCacheID' in struct literal of type openrtb_ext.VideoTargeting
```

Furthermore,  it seems that `dep ensure` installs some other version of the prebid server in the `vendor` directory, and that `go build .` builds from this version, and not the source code of the repo.  I've been cp'ing my changes into the vendor directory to see my work reflected in local builds, but this sometimes results in compilation errors, since the version installed in `vendor` differs from that in master. 

Can someone clarify what the correct process is for developing and testing against this repo?  In particular, how can I 
a) make sure that I'm running all the tests correctly?
b) see the progress of my work reflected in local builds?

**Comment by mansinahar** [comment]
Can I ask what's the path where you have cloned the repo and trying to build it and also, what are your GOPATH and GOROOT environment variables set to?

**Comment by mansinahar** [comment]
I have seen this kind of an issue usually when you have cloned your repo in `$GOPATH/src`. I'd suggest cloning your repo in `$GOPATH/src/github.com/prebid/` and then run `dep ensure`. In this case `dep ensure` shouldn't again pull Prebid-server as a dependency in the `vendor` directory.

**Comment by Kevin-P-Kerr** [comment]
Thanks, re-cloning in `$GOPATH/src/github.com/prebid/` seemed to work.  It's a bit confusing that the readme says to clone in `$GOPATH/src`.

**Comment by mansinahar** [comment]
Yeah, I agree, it can be a little confusing but if you execute the commands specified in the Readme as is, it should have you clone the repo in `$GOPATH/src/github.com/prebid/`

```
cd $GOPATH
git clone https://github.com/prebid/prebid-server src/github.com/prebid/prebid-server
cd src/github.com/prebid/prebid-server
dep ensure
```

Anyway, I am glad it works now :)
